#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
	ALTER USER $APP_USER CREATEDB;
	GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;
EOSQL
